### ISSUE TITLE
Can you provide the code of one of your examples?

### ISSUE THREAD

**Issue by lucasmaffazioli** [sooxt98/google_nav_bar#10]
At the beginning, when you change tabs it appears you're using a TabController? I'm trying to make the TabController animate the GoogleNavBar **while** the user swipes the screen, just like in your example. Thanks!

![image of tabs chaning](https://user-images.githubusercontent.com/13378059/71321360-2b47cc80-24f3-11ea-9b1b-389355ae8661.gif)

**Comment by sooxt98** [comment]
@lucasmaffazioli it's all inside the example folder

**Comment by sooxt98** [comment]
@lucasmaffazioli  It's here https://github.com/sooxt98/google_nav_bar/blob/master/example/lib/main_advance.dart

**Comment by sooxt98** [comment]
oh wait, i think i accidentally remove the code ><

**Comment by sooxt98** [comment]
@lucasmaffazioli It's back now~ @ main_advance.dart

**Comment by lucasmaffazioli** [comment]
Now it's perfect! Beautiful, thanks!
