### ISSUE TITLE
RenderFlex overflow when adding 6 tabs

### ISSUE THREAD

**Issue by trademunch** [sooxt98/google_nav_bar#12]
Unable to add 6 tabs, Gives RenderFlex overflow at right side.

Please suggest so that the space between the tabs can be decreased and 6 tabs can be added easily.

**Comment by sooxt98** [comment]
U need to decrease the padding and gap for the Gbutton or make the text smaller , so u have example screenshot or code?

**Comment by trademunch** [comment]
Image 1:
https://www.dropbox.com/s/sz9wk4jsi38bmfb/image_1.jpg?dl=0

Image 2: 
https://www.dropbox.com/s/jb1pxar7vxfnc07/image_2.jpg?dl=0

In case I decreased the gap and padding for GNav it comes like this, but the last tab has 2 words in it, which again makes it overflow.

Updated the below code:

GNav(
                gap: 5,
                activeColor: Colors.white,
                iconSize: 24,
                padding: EdgeInsets.symmetric(horizontal: 10, vertical: 5),
                duration: Duration(milliseconds: 800),
                tabBackgroundColor: Colors.grey[800],
)

**Comment by sooxt98** [comment]
U need to either cut off the text, or decrease the ‘tabMargin’, ‘gap’, and ‘padding’; the last solution is making the font smaller with ‘textStyle’.

**Comment by trademunch** [comment]
Thanks for the help,
I had to cut short the text and decrease text size as per your suggestion. 
Closing the issue!
