### ISSUE TITLE
RenderFlex

### ISSUE THREAD

**Issue by sayan82** [sooxt98/google_nav_bar#14]
When The Display Size and Font Size are Large then it Shows pixel overflowed.

**Comment by sooxt98** [comment]
any screenshot? It's normal tho I think

**Comment by sayan82** [comment]
where to sent those screenshot??😅

**Comment by sayan82** [comment]
Where to send the screenshot?

**Comment by sooxt98** [comment]
YouTube or just paste here

**Comment by sayan82** [comment]
https://photos.app.goo.gl/cbkTJp1XA8fdVHkZ8

**Comment by sooxt98** [comment]
u need to make ur Gnav wider Abit, cause it don't have space to show Gbutton

**Comment by sayan82** [comment]
Its taking entire width of screen ..how to make it more wider?

**Comment by sooxt98** [comment]
If like so u need to either reduce the gap or padding of navbar and button, and reduce the font and icon size

**Comment by sooxt98** [comment]
Close for idle
