### ISSUE TITLE
Allow icon to take Widget, not IconData

### ISSUE THREAD

**Issue by lukepighetti** [sooxt98/google_nav_bar#16]
We can refactor GButton.icon to be a `Widget` and apply the icon settings as an `IconTheme`. This matches the semantics of other material widgets, and in our case, allows us to put a dynamic icon widget in GNav.

Is this a PR you would accept?

**Comment by sooxt98** [comment]
Yea I think it's okay, but I'll be hard to make it flexible; cause custom widget normally don't have fixed size

**Comment by lukepighetti** [comment]
Can you explain the concern you have? From what I can tell the icons do not change in size and if someone provides a custom widget I believe you can expect them to size it properly to visually match the other icons.

**Comment by sooxt98** [comment]
@lukepighetti normally they want to add badge count above the icon, so if the numbers from 0  - 10 the size of the badge will affect the icon size, may i know what kind of widget u want to put in?

**Comment by lukepighetti** [comment]
We are no longer using this package so you’re welcome to close this issue.

**Comment by sooxt98** [comment]
Fixed in V3
