### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by harpreet9629** [sooxt98/google_nav_bar#18]
E/flutter (21944): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: setState() called after dispose(): _GNavState#81aa2(lifecycle state: defunct, not mounted)
E/flutter (21944): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter (21944): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (21944): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

**Comment by sooxt98** [comment]
hi harpreet, please give me a minimal code which can reproduce this error

**Comment by sooxt98** [comment]
https://stackoverflow.com/questions/49340116/setstate-called-after-dispose
