### ISSUE TITLE
Add badging capabilities for displaying notification counters.

### ISSUE THREAD

**Issue by ngoctranfire** [sooxt98/google_nav_bar#19]
I think this library is really sleek, but I would like to see something like Badges having first-class support in this navigation bar. Are there any plans to add this? If not, I can look into this!

https://pub.dev/packages/badges

**Comment by sooxt98** [comment]
![image](https://user-images.githubusercontent.com/13378059/87547483-bda4fd00-c6dd-11ea-937b-186794a7f64e.png)
@ngoctranfire yes you can look into it, i think it's not hard to add badges to it; try to  wrap the bade around the Icon widget

**Comment by sooxt98** [comment]
Fixed in V3
