### ISSUE TITLE
how to use it in other language 

### ISSUE THREAD

**Issue by faress123** [sooxt98/google_nav_bar#20]
hello everyone,

I use the google_nav_bar package, it is good and very nice. 

but when I convert the direction of the app to (right to left) the text is making an error.

like the photo below:

https://i.ibb.co/D183V9b/20200713-170022.jpg

how can I solve that ??

and I am sorry because my English is not very good

**Comment by sooxt98** [comment]
@faress123 may i know what language are you using?

**Comment by faress123** [comment]
@sooxt98  I using the Arabic language

**Comment by sooxt98** [comment]
I just try with the web; i works fine; maybe it doesn't work on phone? 
![image](https://user-images.githubusercontent.com/13378059/88761033-e5e23080-d1a0-11ea-8df5-ef48633fd705.png)

**Comment by omrid594** [comment]
@sooxt98  you are probably using `MaterialApp`, that's why its showing left to right instead of right to left.
I have the same problem - my app localization is RTL. 
Thats why it showed like this >>
![image](https://user-images.githubusercontent.com/19475206/88769993-d3a6c900-d185-11ea-8b85-65f8dd0662db.png)

Any solution?

**Comment by sooxt98** [comment]
@omrid594 maybe u could try to wrap the navbar with `Directionality` widget

``` dart 
void main() {
  runApp(
    MaterialApp(
      home: Directionality( // add this
        textDirection: TextDirection.rtl, // set this property 
        child: GNav(...),
      ),
    ),
  );
}
```

take a look at here: https://stackoverflow.com/questions/50535185/right-to-left-rtl-in-flutter

**Comment by omrid594** [comment]
@sooxt98 Not working - The issue causes because there is `Row` which contains the `Icon` and `Text` in each GNav.
Because everything it RTL (due to localization) >> **the Icon starts at the right side on each Row**
Any way to move make the `mainAxisAlignment: MainAxisAlignment.end,` inside the Row?

**Comment by sooxt98** [comment]
Did you try `textDirection: TextDirection.ltr` instead of `TextDirection.rtl`

**Comment by omrid594** [comment]
@sooxt98 Great! the order now is backward but works just fine! Thanks a lot

**Comment by faress123** [comment]
the problem still appears, 

I need to make my app always start from right to left, 

but the text appears to a behind of the icon.

like that:

https://i.ibb.co/D183V9b/20200713-170022.jpg

**Any Solutions?**

**Comment by sooxt98** [comment]
@faress123 try wrap your Gnav with `Directionality`

``` dart
void main() {
  runApp(
    MaterialApp(
      home: Directionality( // add this
        textDirection: TextDirection.ltr, // set this property 
        child: GNav(...),
      ),
    ),
  );
}
```

**Comment by faress123** [comment]
@sooxt98 this work fine, and the text appear fine, but the app work from left to right, 
like the photo here:
https://i.ibb.co/mHTq7bN/Screenshot-20200805-161842.jpg

but I need my app to work from right to left ...

**Comment by sooxt98** [comment]
@faress123 for ur case, I need to rewrite the UI & animation to flip the icon & text

**Comment by faress123** [comment]
@sooxt98 
I will be grateful to you, will there appear in the new version?
