### ISSUE TITLE
GButton icon widget

### ISSUE THREAD

**Issue by wesleytoshio** [sooxt98/google_nav_bar#21]
does GButton's icon property accept a widget? Currently it only supports IconData and in my project I need to add the user's photo circled
EX:
![image](https://user-images.githubusercontent.com/7057737/87860991-4effb380-c918-11ea-9e88-fa9ba5d5e502.png)

**Comment by sooxt98** [comment]
Currently nope, here's the work around https://github.com/sooxt98/google_nav_bar/issues/19

**Comment by sooxt98** [comment]
Fixed in V3
