### ISSUE TITLE
Hebrew GNav

### ISSUE THREAD

**Issue by omrid594** [sooxt98/google_nav_bar#22]
Trying to make an RTL NavBar.
But the text gets over the icon.

![image](https://user-images.githubusercontent.com/19475206/88659953-8d4a5f00-d0de-11ea-840c-987f2f3757fe.png)

The localization of the app is RTL (he,IL).
How could it be fixed?

**Comment by sooxt98** [comment]
This issue will move to here https://github.com/sooxt98/google_nav_bar/issues/20
