### ISSUE TITLE
Big grey box when switching pages in release mode

### ISSUE THREAD

**Issue by louia** [sooxt98/google_nav_bar#23]
I have a big grey box  which appear less than one second when switching between page, in release mode or in profile mode.

In profile I was able to get this message error :

`Another exception was thrown: Instance of 'ft'`
or 
`uid=10419(com.***) 1.ui identical 23 lines`

**Comment by sooxt98** [comment]
@louia coild you give me a minimal reproduce code and a screen recording from me?

**Comment by louia** [comment]
I use your example : https://github.com/sooxt98/google_nav_bar/blob/master/example/lib/main_advance.dart

I use the latest stable version of flutter : 1.21.0-10.0.pre.114

And this is the box : 
![Screenshot_20200819-110917](https://user-images.githubusercontent.com/33846211/90615595-a4c3c600-e20c-11ea-9757-4bed8e685feb.jpg)

**Comment by sooxt98** [comment]
@louia i think the latest flutter version breaks the flexbox;

**Comment by louia** [comment]
I also think.
You will provide an update ? I didn't see where will be the error.

**Comment by sooxt98** [comment]
@louia ill try to fix later, Im currently doing V3 and will update my flutter to check whether i can get that glitch

**Comment by sooxt98** [comment]
@louia  i just upgrade my flutter and it's on v1.20.2 with no problem at all

**Comment by louia** [comment]
I was on master channel instead of stable....
master : 1.21
stable : 1.20

Everythink works fine in 1.20 but for now not in 1.21

**Comment by sooxt98** [comment]
@louia i think just let them fix the break;

**Comment by sooxt98** [comment]
@louia hi there, doesn't this issue still exist?

**Comment by sooxt98** [comment]
Flutter 2
