### ISSUE TITLE
Stack is missing overflow parameter in latest Flutter's master branch 

### ISSUE THREAD

**Issue by tsinis** [sooxt98/google_nav_bar#25]
Hey @sooxt98 

Thanks for awesome package. Just want to point you out that in latest Flutter's master brunch there is no "overflow" parameter (that you use in your nav bar), so you will have to migrate to make it work on most recent Flutter version. Here is migration guide from Google:
https://docs.google.com/document/d/1gC5Di4ykTCqupD77PWpy9D8xXo0Ide5CnrH0zzVIhKo/edit#heading=h.qxzs91rbt759

Also attaching Issue from Flutter repo:
https://github.com/flutter/flutter/issues/66030

Thanks in advance!

**Comment by sooxt98** [comment]
Thanks for the find out @tsinis ! I think i would just simply remove the overflow param in next update
