### ISSUE TITLE
Key property for GButton is missing implementation

### ISSUE THREAD

**Issue by r0hit-gupta** [sooxt98/google_nav_bar#27]
Passing `key` property to the `GButton` does nothing. The widget does not contain the passed key. This is required for performing tests using flutter driver.

**Comment by sooxt98** [comment]
https://github.com/sooxt98/google_nav_bar/commit/9ff7f8f4d72abcc0133dfe98e0b224e7ee57f26e

**Comment by r0hit-gupta** [comment]
@sooxt98 you missed passing the key in the map function. I have created a new PR for that. :) https://github.com/sooxt98/google_nav_bar/pull/28
