### ISSUE TITLE
Suggestion for improvements

### ISSUE THREAD

**Issue by Gustav0ar** [sooxt98/google_nav_bar#3]
Firstly, very nice widget, I'll be trying it in my app.

Could you please add badges support for the icon.
Maybe instead of passing the icon, pass a widget, which then I can control how it looks like.
Also do that for text, for more granular control of style.
What do you think?

**Comment by sooxt98** [comment]
@Gustav0ar could you show me the design you want?

**Comment by sooxt98** [comment]
Fixed in V3
