### ISSUE TITLE
Insert Widget to Container page index 0,1,2,3

### ISSUE THREAD

**Issue by mocheffendi** [sooxt98/google_nav_bar#31]
Hi, 

I am new on Flutter, your package is amazing.
How to insert widget to Container on different page index 0,1,2,3 with your package.

Thanks
M. Effendi

**Comment by sooxt98** [comment]
Try running the advance example in the example folder

**Comment by mocheffendi** [comment]
how to insert widget ?

body: PageView.builder(
          onPageChanged: (page) {
            setState(() {
              selectedIndex = page;
              badge = badge + 1;
            });
          },
          controller: controller,
          itemBuilder: (context, position) {
            return Container(
              color: colors[position],
            );
          },
          itemCount: 4, // Can be null
        ),

**Comment by mocheffendi** [comment]
Thanks solved
