### ISSUE TITLE
Feature request: Tooltip or Semantic Label

### ISSUE THREAD

**Issue by tsinis** [sooxt98/google_nav_bar#34]
Hey @sooxt98!

 Writing to you again! Thank you for the great package, but could you add some semantics? Because at the moment GButton doesn't allow us to add any tooltip or semantic tag, so Accessibility Checker or any other semantic analysis SW will not recognize the meaning of this button... Semantics are articularly helpful for people with visual impairments but are also great for testing. A Tooltip would be perfect, but the semanticLabel property should be okay too.

Thanks!

**Comment by tsinis** [comment]
I can make PR probably, if you accept. Thanks.

**Comment by sooxt98** [comment]
Hi @tsinis  why don't just simply wrap Gbutton with tooltips or semantics?

**Comment by tsinis** [comment]
> Hi @tsinis  why don't just simply wrap Gbutton with tooltips or semantics?
> 
> 

Hey! Because GNav "tabs" parameter only accept List<GButton> not List<Widget>. Thanks for reply.

**Comment by sooxt98** [comment]
@tsinis ah so adding one more Tooltip to GButton would be enough? btw, PR is welcome :3

**Comment by tsinis** [comment]
> @tsinis ah so adding one more Tooltip to GButton would be enough? btw, PR is welcome :3

Ok super. I'll try to push a PR in few days so you can review it. Thanks!

**Comment by tsinis** [comment]
Thanks for PR merge @sooxt98 ! Wish you good luck with null-safety, stay strong :D
