### ISSUE TITLE
Add support for border color

### ISSUE THREAD

**Issue by dustincatap** [sooxt98/google_nav_bar#35]
First off, nice plugin! Been using it in some of my flutter apps

Is there anyway to add border color in GButtons?

**Comment by sooxt98** [comment]
Good idea, i'll add it next month

**Comment by sooxt98** [comment]
https://github.com/sooxt98/google_nav_bar/commit/dd4eac02cd9b26f86cd0a4e6dfd1266a3a1d2d4f
