### ISSUE TITLE
How can we add SvgPicture on GButton

### ISSUE THREAD

**Issue by RomjanHossain** [sooxt98/google_nav_bar#38]
GButton takes IconData as an icon! Is there any way to add svgPicture as an icon?

**Comment by sooxt98** [comment]
yep u can, if you look at this example https://github.com/sooxt98/google_nav_bar/blob/master/example/lib/main_advance.dart 
i added the custom badge widget; So you can use pass https://pub.dev/packages/flutter_svg to `leading` options

**Comment by RomjanHossain** [comment]
oh! I haven't look up the contractor, sorry!  thanks for the Great pkg!
