### ISSUE TITLE
CupertinoIcons don't work

### ISSUE THREAD

**Issue by nilsnilsnils** [sooxt98/google_nav_bar#4]
Hi,

I use your bar. It's very nice and simple to use :) Great Work.

When I use `CupertinoIcons` the icons will be shown double / strechted as seen in the screenshot.
e.g.  `              GButton(
                    icon: CupertinoIcons.home,
                    text: 'Home',
                  ),`

normal Icons work like as expected.
e.g. `              GButton(
                    icon: Icons.ac_unit,
                    text: 'Home',
                  ),`

Maybe you have a solution for that. Thanks

![Bildschirmfoto 2020-03-05 um 11 36 53](https://user-images.githubusercontent.com/5464118/75973708-edddc300-5ed5-11ea-8d99-493d3f3794f6.png)

**Comment by sooxt98** [comment]
Issue closed with V2.0.1
https://github.com/sooxt98/google_nav_bar/commit/a966f8aca1fcac737966f0b387224f68fc1c89ce
