### ISSUE TITLE
Rework is needed to animate only icon instead of text

### ISSUE THREAD

**Issue by sooxt98** [sooxt98/google_nav_bar#41]
![ezgif-4-b95a923f690f](https://user-images.githubusercontent.com/13378059/104826607-d7ddb480-5893-11eb-887d-ddceda4bfe5b.gif)

**Comment by SatYu26** [comment]
@sooxt98 hey i would like to work on this. can you tell me how should i approach this or what exactly you are trying to do?

**Comment by sooxt98** [comment]
@SatYu26 since this package released till now i still don't have a nice solution to solve this issue, if you look carefully at the design specs, only the like icon moves when activated, the text just fade in from behind, so the distance of the animated like icon need to calculate based on the text length, but theres no good solution out there to get the text width before rendering;

**Comment by simrat39** [comment]
Idk if this is what you want but I made something similar:
https://github.com/simrat39/animated_fab
The code is a mess but I can work on Google nav bar if this is the effect you're trying to implement

**Comment by SatYu26** [comment]
> Idk if this is what you want but I made something similar:
> https://github.com/simrat39/animated_fab
> My code there is a mess but I can work on google nav bar on the weekend if this is the effect you're trying to implement
> 
> gif for reference:
> ![fab3](https://user-images.githubusercontent.com/37233846/105947425-efe4cf00-601d-11eb-985c-8370f9955f2b.gif)

@simrat39  Yes this seems exactly what @sooxt98 want i guess!

**Comment by sooxt98** [comment]
@simrat39 wow this is what im looking for, but does it support dynamic width?

**Comment by SatYu26** [comment]
> @SatYu26 since this package released till now i still don't have a nice solution to solve this issue, if you look carefully at the design specs, only the like icon moves when activated, the text just fade in from behind, so the distance of the animated like icon need to calculate based on the text length, but theres no good solution out there to get the text width before rendering;

okay that seems to be the problem because if not given proper space for text the icon and text might overlap. 
what if we provide the separate container for text only with transparent background so that text will only take designated space.

**Comment by simrat39** [comment]
> @simrat39 wow this is what im looking for, but does it support dynamic width?

No it's hardcoded but I think I can make it work with dynamic width

**Comment by sooxt98** [comment]
Here's some solution for calculation the text width before it renders, but i think will cause some performance issue as well, still waiting for official solution

https://github.com/flutter/flutter/issues/41707
https://stackoverflow.com/questions/52659759/how-can-i-get-the-size-of-the-text-widget-in-flutter/52991124#52991124

**Comment by SatYu26** [comment]
> Here's some solution for calculation the text width before it renders, but i think will cause some performance issue as well, still waiting for official solution
> 
> [flutter/flutter#41707](https://github.com/flutter/flutter/issues/41707)
> https://stackoverflow.com/questions/52659759/how-can-i-get-the-size-of-the-text-widget-in-flutter/52991124#52991124

this seems to work ig.
but as you mentioned it might create performance issues.

**Comment by sooxt98** [comment]
New approach ⚡️

``` dart
import 'package:flutter/material.dart';
import 'dart:math';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class GButton extends StatelessWidget {
  GButton(this._currentSliderValue, this._icons, this._text);
  final double _currentSliderValue;
  final Icon _icons;
  final String _text;

  double expo(double x) {
    return (x == 0) ? 0 : pow(2, 10 * x - 10).toDouble();
  }

  Widget build(_) {
    return Container(
        padding: EdgeInsets.all(10),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(100),
          color: Colors.pink.shade50,
        ),
        child: Stack(children: [
          Row(mainAxisAlignment: MainAxisAlignment.end, children: [
            Opacity(
              opacity: 0,
              child: _icons,
            ),
            Container(
//               width: double.infinity,

              child: Container(
                //color: Colors.blue.withOpacity(.2),
                child: Align(
                    alignment: Alignment.centerRight,
                    widthFactor: _currentSliderValue,
                    child: Container(
                      //width: 100,
                      //color: Colors.red.withOpacity(.2),
                      child: Opacity(
                        opacity: expo(_currentSliderValue),
                        //width: 100,
                        child: Text(
                          _text,
                          style: TextStyle(color: Colors.pink),
                          textAlign: TextAlign.left,
                        ),
                      ),
                    )),
              ),
            ),
          ]),
          Row(mainAxisAlignment: MainAxisAlignment.end, children: [
            _icons,
            Container(
//               width: double.infinity,

              child: Container(
                //color: Colors.blue.withOpacity(.2),
                child: Align(
                    alignment: Alignment.centerRight,
                    widthFactor: _currentSliderValue,
                    child: Opacity(
                      opacity: 0,
                      //width: 100,
                      child: Text(
                        _text,
                        textAlign: TextAlign.left,
                      ),
                    )),
              ),
            ),
          ]),
        ]));
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  double _currentSliderValue = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Container(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Slider(
                value: _currentSliderValue,
                min: 0,
                max: 1,
                //divisions: 5,
                label: _currentSliderValue.round().toString(),
                onChanged: (double value) {
                  setState(() {
                    _currentSliderValue = value;
                  });
                },
              ),
              Row(mainAxisAlignment: MainAxisAlignment.end, children: [
                Text('heiyaaaa'),
                GButton(_currentSliderValue,
                    Icon(Icons.home, color: Colors.pink), 'Naiseeeeee'),
                SizedBox(width: 100)
              ])
            ],
          ),
        ));
  }
}

```
