### ISSUE TITLE
Riple radius doesn't change along with the tabBorderRadius

### ISSUE THREAD

**Issue by SilkeNL** [sooxt98/google_nav_bar#44]
When I set the tabBorderRadius to 8 the ripple stays rounded as if its 15. This causes it to look odd and I can't seem to change it.

https://user-images.githubusercontent.com/49638868/108977302-b046ec80-7688-11eb-9f7d-0a6e31df3ab2.mov

Code:

`
Container(
      child: GNav(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        backgroundColor: Color(0xFF279B40),
        tabBackgroundGradient: LinearGradient(
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
            colors: [Color(0xFF7FCC27), Color(0xFF279B40)]),
        rippleColor: Color(0xFF7FCC27),
        hoverColor: Color(0xFF7FCC27),
        tabBorderRadius: 8,
        tabBorder: Border.all(color: Colors.white, width: 1),
        duration: Duration(milliseconds: 300),
        gap: 8,
        color: Colors.white,
        activeColor: Colors.white,
        curve: Curves.easeIn,
        iconSize: 24,
        padding: EdgeInsets.symmetric(horizontal: 20, vertical: 5),
        tabs: [
          GButton(
            icon: Icons.notifications,
            text: 'Notifications',
          ),
          GButton(
            icon: Icons.home,
            text: 'Dashboard',
          ),
        ],
        selectedIndex: this.activeIndex,
        onTabChange: (index) => onTap(index),
      ),
        );`

**Comment by sooxt98** [comment]
@SilkeNL Fixed in master branch! I'll publish to pub.dev after finishing old issue https://github.com/sooxt98/google_nav_bar/commit/c955155198d0130d284f11736d5701ad193b60ea#diff-b3a9f6e65be382a079e4fffcc8c4bfce57a688dc090e8cacf1477fb19ccaff19
