### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by brizaldi** [sooxt98/google_nav_bar#45]
Is there any plans to add null safety support?

**Comment by sooxt98** [comment]
Hmmmm, not sure what's the benefit using it; for now I think all of the param is nullable

**Comment by Ascenio** [comment]
@sooxt98 yes, but a project can not run full null-safety until all it's dependencies have migrated. If at least one of them is not null safe, then your project works with [unsound null safety](https://dart.dev/null-safety/unsound-null-safety).

**Comment by leynier** [comment]
Any update about this guys? I could help with this.
