### ISSUE TITLE
Updating selectedIndex does not update the index

### ISSUE THREAD

**Issue by JagandeepBrar** [sooxt98/google_nav_bar#48]
Previously on 4.0.2, if I called `setState()` on a value passed to `GNav`, it would also animate the tab to the new index. This no longer works with 5.0.1.

A quick example where I use a `PageController` listener to update `_index`:

```dart
int _index;

@override
void initState() {
    _index = widget.pageController?.initialPage ?? 0;
    widget.pageController?.addListener(_pageControllerListener);
    super.initState();
}

@override
void dispose() {
    widget.pageController?.removeListener(_pageControllerListener);
    super.dispose();
}

void _pageControllerListener() {
    setState(() => _index = widget.pageController.page.round());
}

@override
Widget build(BuildContext context) => GNav(
    selectedIndex: _index,
    ... // Additional GNav parameters
);
```

The initially selected index is correct, but just does not update unless you tap on the `GButton` in the navigation bar.

**Comment by sooxt98** [comment]
@JagandeepBrar Thanks for the testing; I think this is is due to the null-safety refactor by @Ascenio 

![image](https://user-images.githubusercontent.com/13378059/110796927-7ba37980-82b3-11eb-8c09-701a6573a0af.png)

I think i would simply move back the
``` dart
selectedIndex = widget.selectedIndex;
```
back into build function to solve this issue, without having to use `didUpdateWidget `

**Comment by Ascenio** [comment]
I'm sorry for introducing this bug, but I think there shoudln't be logic into build method which could be extracted to elsewhere. I don't think the index should be updated at each build.

Anyway. Fortunately @JagandeepBrar made a change which I checked already and it seems to be working.

**Comment by JagandeepBrar** [comment]
As @Ascenio mentioned, the more "correct" way is to not update values constantly within the build function, and instead use `didUpdateWidget` as used in the pull request I have opened 🙂

**Comment by sooxt98** [comment]
https://pub.dev/packages/google_nav_bar/versions/5.0.2
