### ISSUE TITLE
Compatibility issues after null safety migration

### ISSUE THREAD

**Issue by sooxt98** [sooxt98/google_nav_bar#51]
@Ascenio Did you know why it's not compatible with Flutter 1.22.6?
![image](https://user-images.githubusercontent.com/13378059/111062125-079ae880-84e2-11eb-8c95-40679b59ade8.png)

**Comment by Ascenio** [comment]
It's because as from version 5 and latter the minimum SDK is 2.12.0, which is required to support null safety. But, because of that, version 1.22.6 doesn't meet the minimum SDK. Isn't that big of a deal, it just means that anyone which intends to use version 5+ will need flutter's 2.0+.

**Comment by sooxt98** [comment]
@Ascenio it is because I saw alot of nullsafty still supporting older version. I think maybe we just tweak down the min requirement ?

**Comment by Ascenio** [comment]
Not sure about that. The ones I see compatible with both flutter's 2.0 and 1.22.6 are versions which aren't null safe. A example would be [GetX](https://pub.green/packages/get), the version compatible with both is not the null safe version.

**Comment by sooxt98** [comment]
@Ascenio check this out https://pub.green/packages/bottom_navy_bar

**Comment by Ascenio** [comment]
This package is only compatible with all versions because it has not migrated to null safety. The version you see there is 5.6.0, which has `sdk: ">=2.2.2 <3.0.0"`.

**Comment by Ascenio** [comment]
Actually they have a null safety version, but the one you see at pub.dev is not the safe version.

**Comment by sooxt98** [comment]
@Ascenio hah I see, they hide it in pre-release
