### ISSUE TITLE
Using label text only

### ISSUE THREAD

**Issue by brizaldi** [sooxt98/google_nav_bar#52]
Is there a way to use label text only without icon?

**Comment by sooxt98** [comment]
@brizaldi i wonder what would it look like without icon; could you show me some sketch / UI?

**Comment by brizaldi** [comment]
maybe something like this
![Screenshot 2021-03-18 180258](https://user-images.githubusercontent.com/41714881/111616193-3253ac80-8814-11eb-9fb4-e3020172f853.png)

**Comment by sooxt98** [comment]
@brizaldi You could check out this plugin https://medium.com/android-news/flutter-bubble-tab-indicator-for-tabbar-dd038f1076d3

**Comment by brizaldi** [comment]
for now I managed to complete it using CupertinoSlidingSegmentedControl, but there's not much customization on that widget
