### ISSUE TITLE
GButton onPressed doesn't do anything

### ISSUE THREAD

**Issue by Eva99Cn** [sooxt98/google_nav_bar#57]
Hi, first of all I really like this widget, however I doesn't use it as a bottom navigation bar, but as an appbar, I have a problem for GButton the onPressed function doesn't do anything

**Comment by sooxt98** [comment]
DId you wrap the GButton inside Gnav? If not u probably need to specify `active` param as well

**Comment by Eva99Cn** [comment]
Yes it is wrapped in Gnav.

**Comment by sooxt98** [comment]
Oh i just found something, onPressed wont with Gnav for now, im working on a fix;

**Comment by sooxt98** [comment]
`google_nav_bar: ^5.0.5` Fixed

**Comment by Eva99Cn** [comment]
Thank you !
