### ISSUE TITLE
google_nav_bar 5.0.5  make text visible

### ISSUE THREAD

**Issue by spacekestrel** [sooxt98/google_nav_bar#64]
Can i make text always visible and tab without an icon?

**Comment by sooxt98** [comment]
@spacekestrel yes you can, but without Gnav

```dart
Container(
  child: Row(
    mainAxisAlignment: MainAxisAlignment.spaceBetween,
    child: [
      GButton(
        active: true,
        icon: LineIcons.home,
        text: 'Home',
      ),
      GButton(
        active: true,
        icon: LineIcons.heart_o,
        text: 'Likes',
      ),
      GButton(
        active: true,
        icon: LineIcons.search,
        text: 'Search',
      ),
      GButton(
        active: true,
        icon: LineIcons.user,
        text: 'Profile',
      )
    ]
  )
)
```

**Comment by spacekestrel** [comment]
> 
> 
> @spacekestrel for now, yes you can, but without Gnav
> 
> ```dart
> Container(
>   child: Row(
>     mainAxisAlignment: MainAxisAlignment.spaceBetween,
>     child: [
>       GButton(
>         active: true,
>         icon: LineIcons.home,
>         text: 'Home'
>       ),
>       GButton(
>         active: true,
>         icon: LineIcons.heart_o,
>         text: 'Likes'
>       ),
>       GButton(
>         active: true,
>         icon: LineIcons.search,
>         text: 'Search'
>       ),
>       GButton(
>         active: true,
>         icon: LineIcons.user,
>         text: 'Profile'
>       )
>     ]
>   )
> )
> ```
> 
> In future, user are able to specify `expandedTab: true` to Gnav to expand all GButton by default

Okay, thanks.
