### ISSUE TITLE
 How to assign SvgPicture to 'int' type parameter? #67 

### ISSUE THREAD

**Issue by sanjhi** [sooxt98/google_nav_bar#68]
I am trying to add SVG image as an icon in GButton, but it is not working. Please see the screenshot of error and guide how to resolve it?
![error screenshot](https://user-images.githubusercontent.com/9048643/136890741-f42a6804-5f9d-479a-97c1-ca1ea93b1c89.png)

**Comment by sooxt98** [comment]
Use leading param
``` dart
Gbutton(leading: SvgPicture.asset())
```
https://github.com/sooxt98/google_nav_bar/issues/38

**Comment by alpondith** [comment]
> Use leading param
> 
> ```dart
> Gbutton(leading: SvgPicture.asset())
> ```
> 
> #38

This tells me : The named parameter icon is required. 

I think icon should be nullable.

**Comment by sooxt98** [comment]
The icon is for fallback purpose,
simply place put one icon to it

**Comment by alpondith** [comment]
````
GButton(
  leading: SvgPicture.asset(
    "path",
    height: 24,
    width: 24,
  ),
  icon: Icons.home,
  text: 'Home',
),
```

I was getting run time error. Finally i found the reason. While using SvgPicture the height and width must be given. Sharing the code if it helps somebody like me.
