### ISSUE TITLE
wrong version # in your docs

### ISSUE THREAD

**Issue by ajonno** [sooxt98/google_nav_bar#7]
you show this in the docs:
```
dependencies:
  google_nav_bar: ^2.1.0
```

it should be this:
```
dependencies:
  google_nav_bar: ^2.0.1
```

**Comment by sooxt98** [comment]
Thanks for the note 🎉

**Comment by sooxt98** [comment]
@ajonno where did you found that error, i can't find it tho

**Comment by adrianvintu** [comment]
What is the version that has the `margin` added?

The comments here https://github.com/sooxt98/google_nav_bar say 2.1.0

but I get

```
Because YOURPROJ depends on google_nav_bar ^2.1.0 which doesn't match any versions, version solving failed.
pub get failed (1; Because the_wind_method depends on google_nav_bar ^2.1.0 which doesn't match any versions, version solving failed.)
exit code 1
```

**Comment by SogoGolf** [comment]
Use google_nav_bar: ^2.0.1

**Comment by SogoGolf** [comment]
> @ajonno where did you found that error, i can't find it tho

Its at the bottom of the README.md

**Comment by sooxt98** [comment]
i forgot to release 2.1.0 😂

**Comment by sooxt98** [comment]
![image](https://user-images.githubusercontent.com/13378059/76856998-7aea2a00-688f-11ea-8d81-074b971f3ddb.png)
Here you go~

**Comment by adrianvintu** [comment]
Thank you!
