### ISSUE TITLE
google_nav_bar events

### ISSUE THREAD

**Issue by Hanousi** [sooxt98/google_nav_bar#70]
Hello! Love this project, it looks great and works really well.

One small qualm I have is documentation :( I was wondering if any events are fired off that I can catch when users change between tabs, both when swiping or using the navbar itself.

Keep up the good work and thank you very much!

**Comment by sooxt98** [comment]
@Hanousi do check at the example
https://github.com/sooxt98/google_nav_bar/blob/master/example/lib/main_advance.dart
