### ISSUE TITLE
use image instead of icon

### ISSUE THREAD

**Issue by briouyahasnae** [sooxt98/google_nav_bar#71]
How can i use image instead of icon?

**Comment by briouyaasmae** [comment]
I wanna do the same, I wanna controle the image that's mean change the color of image if the button is active or not

**Comment by sooxt98** [comment]
@briouyaasmae check this https://github.com/sooxt98/google_nav_bar/issues/58


@briouyaasmae  please check to example on how i handle the badge count
https://github.com/sooxt98/google_nav_bar/blob/master/example/lib/main_advance.dart

**Comment by Sher0p** [comment]
By use of leading i can use image but still the text is not shwoing .Any work Around ?
