### ISSUE TITLE
how to remove elevation from the nav bar

### ISSUE THREAD

**Issue by Salam-pc** [sooxt98/google_nav_bar#79]
![image](https://user-images.githubusercontent.com/89230970/169227682-c3027c88-ddb3-4c05-b4af-dd7c520c1d3a.png)

**Comment by sooxt98** [comment]
There’s no elevation within this package, it’s from elsewhere, try look
around your code.

**Comment by sooxt98** [comment]
For example boxShadow

**Comment by razvanduta21** [comment]
1. Wrap it in a Container.

2. If you have something like that delete the boxShadow

return Container(
decoration: BoxDecoration(   
..... 
       boxShadow: [
            color: Colors.black,
            offset: Offset(0, 3),
            blurRadius: 7,
            spreadRadius: 5,         
      ],
),
      child: GNav(tabs: ....),  
    );
  }
}
