### ISSUE TITLE
Skip animation on middle element when you go from first one to last one

### ISSUE THREAD

**Issue by afijal** [sooxt98/google_nav_bar#8]
Hi, I really like your lib and the amount of customization.
I have a PageView as a body and use your package as a bottom navigation bar.
I have 3 pages, when I go from 1 -> 3 then the 2nd one also gets highlighted on the navigation bar, which doesn't look very nice.

Would it be possible to fix it or add a new param?
Let me know if you need a gif, but I guess the description is clear.
If you are busy maybe I will be able to fix it and add PR, let me know your thoughts.

**Comment by sooxt98** [comment]
@afijal I'm still thinking the possible solution, my first idea is put some delay when page changed, if the page stop changing then execute the animation.

This is the issue im facing now :3 need some idea on how to fix it
![ezgif-6-955bfc2f782d](https://user-images.githubusercontent.com/13378059/77146071-216b4080-6ac5-11ea-8de1-7c30c29d9b6f.gif)

**Comment by afijal** [comment]
I found a workaround but this is not directly linked to you library.

My concept:
1. store _page locally and update it in your onTabChange callback
2. In PageView onPageChanged update _page only if user did change it by swiping (this gets called when going 1 -> 3 by click on bottom nav bar 2 times, that is the root cause)

Issues:
-can't really detect swipe, wrapping in GestureDetector didn't help

Hack:
1. Have a state variable named e.g. _justClicked = false
2. Set it to true in onTabChange and then after delay to false
3. In PageView onPageChanged set _page only if _justclicked = false

This works fine but feel a bit hacky
![image](https://user-images.githubusercontent.com/2682379/77206677-cf8fde00-6af7-11ea-8440-0c931bcb3532.png)

**Comment by sooxt98** [comment]
@afijal i think I have misunderstood your issue, how do you go from tab 1 to tab3? By swiping or tapping? Could you show me a gif or explain more Abit?

Here's a example repo you could refer to which I think your issue is not happening here, you could try run it see if the issue is there.
https://github.com/tayormi/covid_tracker

**Comment by sooxt98** [comment]
@afijal oh I get it, you are using the view pager animation when switching between tabs, that's why the navbar animations are being triggered. Yep put delay will definitely solve the issue, the delay time can set as same as the navbar duration

**Comment by afijal** [comment]
Yeah I should have explained it better.
Thanks!
