### ISSUE TITLE
how to make resize screen ?

### ISSUE THREAD

**Issue by AcarFurkan** [sooxt98/google_nav_bar#80]
https://user-images.githubusercontent.com/65075121/183116695-c6fd7825-0bd6-4b7f-b790-4caf5e86978b.mp4

**Comment by sooxt98** [comment]
sorry, i don't understand what you mean

**Comment by AcarFurkan** [comment]
I want the screen size to change when the keyboard is opened. I want the .bottombar to rise above the keyboard.

**Comment by sooxt98** [comment]
Try to take a look at this, this issue is not related to this plugin but
the way on how you wrap the Gnvav

https://stackoverflow.com/questions/52350371/bottom-navigation-bar-sticks-to-top-of-keyboard
