### ISSUE TITLE
The bar overflows on small screens and throws error

### ISSUE THREAD

**Issue by zulkarnainshah** [sooxt98/google_nav_bar#88]

**Comment by zulkarnainshah** [comment]
![Screenshot 2023-03-31 at 8 10 01 AM](https://user-images.githubusercontent.com/12382340/229009289-12bf2e89-398b-4e62-9ad7-84b193b9538d.png)

**Comment by sooxt98** [comment]
https://github.com/sooxt98/google_nav_bar/issues/12

**Comment by Wizely99** [comment]
wrapping it in a `FittedBox` Widget solved the error for me
