### ISSUE TITLE
Is there anyway to use a gradient color as backgroundcolor for the Gbuttons?

### ISSUE THREAD

**Issue by ChristBKK** [sooxt98/google_nav_bar#9]
Is there anyway to use a gradient color as backgroundcolor for the Gbuttons?

**Comment by sooxt98** [comment]
Try using https://api.flutter.dev/flutter/dart-ui/Shader-class.html

**Comment by Kiruel** [comment]
Have you find something @ChristBKK ? I can maybe create a PR if not.

**Comment by sooxt98** [comment]
New version released @ 2.2.0

**Comment by ChristBKK** [comment]
thanks will update. @Kiruel  I didn't need it anymore currently, but I will check the new version and test it out.

Great package so far @sooxt98  keep up the good work.

**Comment by ChristBKK** [comment]
@sooxt98  just a thought, maybe rename the package to "google_navigation_bar" I think a lot of people search navigation bar first in pub dart / flutter. I searched that too. Your appbar is currently one of the best maintained ones of the beautiful ones :)
